CREATE TABLE IF NOT EXISTS inquiries (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL,
	subject VARCHAR(150) NOT NULL,
	message TEXT NOT NULL,
	admin_reply TEXT,
	replied_at DATETIME,
	status VARCHAR(20) NOT NULL DEFAULT 'NEW',
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);

ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS admin_reply TEXT;
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS replied_at DATETIME;

CREATE TABLE IF NOT EXISTS members (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	points INT NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);
