CREATE TABLE IF NOT EXISTS inquiries (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL,
	subject VARCHAR(150) NOT NULL,
	message TEXT NOT NULL,
	admin_reply TEXT,
	replied_at DATETIME,
	status VARCHAR(20) NOT NULL DEFAULT 'NEW',
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);

ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS admin_reply TEXT;
ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS replied_at DATETIME;

CREATE TABLE IF NOT EXISTS inquiry_replies (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	inquiry_id BIGINT NOT NULL,
	recipient_email VARCHAR(255) NOT NULL,
	reply TEXT NOT NULL,
	sent_at DATETIME NOT NULL,
	created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS members (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	points INT NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS hamsters (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	species VARCHAR(100) NOT NULL,
	sex VARCHAR(20) NOT NULL,
	birth_date DATE NOT NULL,
	health_condition VARCHAR(255) NOT NULL,
	arrival_date DATE NOT NULL,
	status VARCHAR(20) NOT NULL,
	notes TEXT,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);

ALTER TABLE hamsters ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE hamsters ADD COLUMN IF NOT EXISTS health_condition VARCHAR(255) DEFAULT '店頭で個別管理';
UPDATE hamsters SET birth_date = COALESCE(birth_date, arrival_date);
UPDATE hamsters SET health_condition = COALESCE(health_condition, '店頭で個別管理');
ALTER TABLE hamsters DROP COLUMN IF EXISTS age_description;
